In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!unzip /content/drive/MyDrive/TSPNet/data-bin/data-bin.zip

Archive:  /content/drive/MyDrive/TSPNet/data-bin/data-bin.zip
   creating: data-bin/phoenix2014T/
   creating: data-bin/phoenix2014T/sp25000/
  inflating: data-bin/phoenix2014T/sp25000/valid.sign-de.sign  
  inflating: data-bin/phoenix2014T/sp25000/valid.sign-de.de  
  inflating: data-bin/phoenix2014T/sp25000/test.sign-de.sign  
  inflating: data-bin/phoenix2014T/sp25000/emb  
  inflating: data-bin/phoenix2014T/sp25000/test.sign-de.de  
  inflating: data-bin/phoenix2014T/sp25000/dict.de.txt  
  inflating: data-bin/phoenix2014T/sp25000/train.sign-de.sign  
  inflating: data-bin/phoenix2014T/sp25000/preprocess.log  
  inflating: data-bin/phoenix2014T/sp25000/train.sign-de.de  


In [ ]:
/content/data-bin/phoenix2014T/sp25000/emb

In [3]:
!unzip /content/drive/MyDrive/TSPNet/I3D-features/span=12_stride=2.zip

Streaming output truncated to the last 5000 lines.
  inflating: span=12_stride=2/08December_2009_Tuesday_heute-4208.pt  
  inflating: span=12_stride=2/08December_2009_Tuesday_heute-4219.pt  
  inflating: span=12_stride=2/08December_2009_Tuesday_tagesschau-1933.pt  
  inflating: span=12_stride=2/08February_2010_Monday_heute-1505.pt  
  inflating: span=12_stride=2/08February_2010_Monday_tagesschau-2804.pt  
  inflating: span=12_stride=2/08February_2010_Monday_tagesschau-2805.pt  
  inflating: span=12_stride=2/08January_2010_Friday_tagesschau-3982.pt  
  inflating: span=12_stride=2/08January_2010_Friday_tagesschau-3986.pt  
  inflating: span=12_stride=2/08July_2010_Thursday_tagesschau-5383.pt  
  inflating: span=12_stride=2/08May_2010_Saturday_tagesschau-182.pt  
  inflating: span=12_stride=2/08May_2010_Saturday_tagesschau-183.pt  
  inflating: span=12_stride=2/08May_2010_Saturday_tagesschau-185.pt  
  inflating: span=12_stride=2/08November_2010_Monday_heute-6878.pt  
  inflating: span=12

In [5]:
import torch
k = torch.load('/content/span=12_stride=2/01April_2010_Thursday_heute-6694.pt')

In [7]:
k=torch.stack(k)

In [8]:
k.shape

torch.Size([27, 1, 1024])

In [9]:
k

tensor([[[2.0362e-03, 4.4862e-03, 3.4768e-02,  ..., 5.0220e-01,
          2.4075e-01, 1.7794e-01]],

        [[2.1397e-03, 0.0000e+00, 2.3792e-02,  ..., 3.6907e-01,
          2.2425e-01, 1.6381e-01]],

        [[6.0819e-05, 0.0000e+00, 8.6738e-03,  ..., 5.8668e-01,
          2.5996e-01, 2.5412e-01]],

        ...,

        [[3.0667e-02, 2.3715e-01, 5.1970e-02,  ..., 7.3016e-02,
          3.8085e-01, 1.9483e-01]],

        [[2.8900e-02, 1.4489e-01, 8.2287e-03,  ..., 8.2262e-02,
          4.2445e-01, 1.8135e-01]],

        [[2.9346e-02, 5.4170e-03, 0.0000e+00,  ..., 1.0725e-01,
          3.8935e-01, 1.6665e-01]]])

In [12]:
k = torch.squeeze(k,dim=1)

In [13]:
k

tensor([[2.0362e-03, 4.4862e-03, 3.4768e-02,  ..., 5.0220e-01, 2.4075e-01,
         1.7794e-01],
        [2.1397e-03, 0.0000e+00, 2.3792e-02,  ..., 3.6907e-01, 2.2425e-01,
         1.6381e-01],
        [6.0819e-05, 0.0000e+00, 8.6738e-03,  ..., 5.8668e-01, 2.5996e-01,
         2.5412e-01],
        ...,
        [3.0667e-02, 2.3715e-01, 5.1970e-02,  ..., 7.3016e-02, 3.8085e-01,
         1.9483e-01],
        [2.8900e-02, 1.4489e-01, 8.2287e-03,  ..., 8.2262e-02, 4.2445e-01,
         1.8135e-01],
        [2.9346e-02, 5.4170e-03, 0.0000e+00,  ..., 1.0725e-01, 3.8935e-01,
         1.6665e-01]])

In [16]:
import os
len(os.listdir('span=12_stride=2'))

8257

In [17]:
8257-(519+642)

7096

In [18]:
!wget "http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.train"

--2020-12-15 17:19:56--  http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.train
Resolving cihancamgoz.com (cihancamgoz.com)... 192.232.218.145
Connecting to cihancamgoz.com (cihancamgoz.com)|192.232.218.145|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1935289362 (1.8G)
Saving to: ‘phoenix14t.pami0.train’

phoenix14t.pami0.tr 100%[===================>]   1.80G  6.93MB/s    in 80s     

2020-12-15 17:21:16 (23.1 MB/s) - ‘phoenix14t.pami0.train’ saved [1935289362/1935289362]



In [61]:
!wget "http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.test"

--2020-12-15 18:12:11--  http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.test
Resolving cihancamgoz.com (cihancamgoz.com)... 192.232.218.145
Connecting to cihancamgoz.com (cihancamgoz.com)|192.232.218.145|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151327204 (144M)
Saving to: ‘phoenix14t.pami0.test’

phoenix14t.pami0.te 100%[===================>] 144.32M  38.8MB/s    in 4.1s    

2020-12-15 18:12:15 (35.1 MB/s) - ‘phoenix14t.pami0.test’ saved [151327204/151327204]



In [63]:
import pickle
import gzip

def load_dataset_file(filename):
  with gzip.open(filename, "rb") as f:
    loaded_object = pickle.load(f)
    return loaded_object

p = load_dataset_file('phoenix14t.pami0.test')

names = []
for i in range(len(p)):
  names.append(p[i]['name'])

p

[{'gloss': 'REGEN SCHNEE REGION VERSCHWINDEN NORD REGEN KOENNEN REGION STERN KOENNEN SEHEN',
  'name': 'test/25October_2010_Monday_tagesschau-17',
  'sign': tensor([[1.2158, 0.0000, 0.4402,  ..., 0.0000, 0.0000, 0.0000],
          [1.3111, 0.0000, 0.6121,  ..., 0.0000, 0.0000, 0.0000],
          [0.8424, 0.0000, 0.3777,  ..., 0.2220, 0.0000, 0.0000],
          ...,
          [5.4710, 0.0266, 0.0252,  ..., 0.0000, 0.0000, 0.0000],
          [1.5307, 0.2369, 0.3094,  ..., 0.0000, 0.0000, 0.0000],
          [1.3268, 0.4522, 0.3599,  ..., 0.0000, 0.0000, 0.0000]]),
  'signer': 'Signer01',
  'text': 'regen und schnee lassen an den alpen in der nacht nach im norden und nordosten fallen hier und da schauer sonst ist das klar .'},
 {'gloss': 'DONNERSTAG NORDWEST REGEN REGION SONNE WOLKE WECHSELHAFT DANN FREITAG AEHNLICH WETTER',
  'name': 'test/25October_2010_Monday_tagesschau-24',
  'sign': tensor([[0.0000, 0.0000, 0.5131,  ..., 0.0000, 0.0000, 0.0000],
          [0.0574, 0.0051, 0.5100,  ...

In [65]:
import pickle
import gzip

def load_dataset_file(filename):
  with gzip.open(filename, "rb") as f:
    loaded_object = pickle.load(f)
    return loaded_object

p = load_dataset_file('phoenix14t.pami0.train')

names = []
for i in tqdm(range(len(p))):
  names.append(p[i]['name'])



100%|██████████| 7096/7096 [00:00<00:00, 1651836.01it/s]


In [66]:
names[0]

'train/11August_2010_Wednesday_tagesschau-1'

In [67]:
names = list(map(lambda x: 'span=12_stride=2/'+x.split('/')[1]+'.pt',names))

In [68]:
names[0]

'span=12_stride=2/11August_2010_Wednesday_tagesschau-1.pt'

In [69]:
os.path.join('train',names[0].split('/')[1]).split('.')[0]


'train/11August_2010_Wednesday_tagesschau-1'

In [70]:
import tensorflow as tf
import numpy as np
os.makedirs('train')
l = []
ref = np.random.randn(238,1024)
for i in tqdm(names):
  path = os.path.join('train',i.split('/')[1]).split('.')[0]

  val = np.asarray(torch.squeeze(torch.stack(torch.load(i)),dim=1),dtype = np.float32)
  l.append(val.shape[0])
  sequence = [val,ref]
  k = tf.keras.preprocessing.sequence.pad_sequences(sequence, padding='post', dtype = 'float32')
  np.save(str(path),k[0,:,:])



  0%|          | 0/7096 [00:00<?, ?it/s]

  0%|          | 11/7096 [00:00<01:05, 108.44it/s]

  0%|          | 24/7096 [00:00<01:02, 113.98it/s]

  1%|          | 37/7096 [00:00<01:00, 117.52it/s]

  1%|          | 52/7096 [00:00<00:56, 124.54it/s]

  1%|          | 71/7096 [00:00<00:50, 138.89it/s]

  1%|          | 84/7096 [00:00<00:51, 135.92it/s]

  1%|▏         | 98/7096 [00:00<00:51, 134.82it/s]

  2%|▏         | 112/7096 [00:00<00:51, 135.82it/s]

  2%|▏         | 126/7096 [00:00<00:55, 124.69it/s]

  2%|▏         | 139/7096 [00:01<01:00, 115.64it/s]

  2%|▏         | 155/7096 [00:01<00:55, 125.14it/s]

  2%|▏         | 169/7096 [00:01<00:53, 128.41it/s]

  3%|▎         | 183/7096 [00:01<00:55, 123.94it/s]

  3%|▎         | 197/7096 [00:01<00:53, 127.92it/s]

  3%|▎         | 211/7096 [00:01<00:53, 129.78it/s]

  3%|▎         | 227/7096 [00:01<00:50, 137.27it/s]

  3%|▎         | 241/7096 [00:01<00:55, 124.56it/s]

  4%|▎         | 256/7096 [00:01<00:53, 126.68it/s]

  4%|▍   

In [45]:
!pip install -U tqdm
from tqdm import tqdm


 41%|████▏     | 2942/7096 [02:15<01:44, 39.61it/s]

     |████████████████████████████████| 71kB 5.1MB/s 
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1


In [74]:
np.load('train/'+os.listdir('train')[0])

array([[0.        , 0.        , 0.03035177, ..., 0.25864902, 0.49432915,
        0.09388632],
       [0.        , 0.01515201, 0.10927103, ..., 0.1223332 , 0.3789098 ,
        0.06428001],
       [0.00348915, 0.        , 0.1030984 , ..., 0.2666798 , 0.35859492,
        0.11406913],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [77]:
torch.squeeze(torch.stack(torch.load('span=12_stride=2/'+os.listdir('train')[0].split('.')[0]+'.pt')),dim=1)

tensor([[0.0000, 0.0000, 0.0304,  ..., 0.2586, 0.4943, 0.0939],
        [0.0000, 0.0152, 0.1093,  ..., 0.1223, 0.3789, 0.0643],
        [0.0035, 0.0000, 0.1031,  ..., 0.2667, 0.3586, 0.1141],
        ...,
        [0.0442, 0.0000, 0.0227,  ..., 0.2534, 0.3810, 0.1342],
        [0.0405, 0.0000, 0.0085,  ..., 0.1378, 0.3310, 0.1778],
        [0.0303, 0.0153, 0.0000,  ..., 0.1415, 0.5001, 0.0784]])

In [78]:
!pip install tokenizers
!pip install sacrebleu

     |████████████████████████████████| 2.9MB 15.7MB/s 
     |████████████████████████████████| 71kB 6.3MB/s 


In [87]:
!python decoder_split.py -train_dir ./phoenix14t.pami0.train  -test_dir ./phoenix14t.pami0.test  -num_layers_enc 3  -num_layers_dec 3  -caption_dir ./en_caption_dir.txt  -BATCH_SIZE 32  -EPOCHS 0  -use_cache 1  -use_gpu 0  -num_heads 8  -dropout_rate 0.1  -use_colab 1


2020-12-15 20:00:28.165045: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-15 20:00:32.195094: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-12-15 20:00:32.252255: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-15 20:00:32.252926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.73GiB deviceMemoryBandwidth: 298.08GiB/s
2020-12-15 20:00:32.252971: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-15 20:00:32.500299: I tensorflow/stream_executor/platform/default